public class AccountHandler {
    public static Account insertNewAccount(String name) {
        Account acct = new Account();
        acct.Name = name;
        try {
            insert acct; 
            Return acct;
        }catch (DmlException e) {
            System.debug('A DML exception has occurred: ' + 
                        e.getMessage());
            return null;
        }
        
    }
}